- Dockerfile
/cc @codeclimate/review 
@pbrisbin is this what you had in mind for the way engines should add the user?
> Add app user

- Gemfile
- Gemfile.lock
- circle.yml
- lib/cc/engine/rubocop.rb
- spec/cc/engine/rubocop_spec.rb
- spec/spec_helper.rb
/cc @codeclimate/review 
The Syntax check returns a different location object than all the other checks
> Handle alternate location class

- bin/codeclimate-rubocop
- lib/cc/engine/rubocop.rb
- spec/cc/engine/rubocop_spec.rb
/cc @codeclimate/review 
I also switched this up to match other engines (accept the hash of the config, rather than the json string)
> Read config from json file

- Gemfile.lock
It should return 0 issue if this option is set to true
> Fix issue with DisabledByDefault in rubocop config file 

- lib/cc/engine/rubocop.rb
- spec/cc/engine/rubocop_spec.rb
> Support both include_paths and exclude_paths in config.json.

- WERE_HIRING.md
@noahd1 pretty sure this is the file Bryan was referring to. Want me to drop it into all the open source engines?
> We're hiring!

- lib/tasks/docs.rake
* Replace @example syntax with Markdown header
* Only replace the first comment hash to preserve in-example comment lines
* Indent code lines
> Improve content formatting

- base_rubocop.yml
Applies this [change][] in our styleguide config.
[change]: https://github.com/codeclimate/styleguide/pull/40
> Update RuboCop `Style/PercentLiteralDelimiters` cop config values

- Gemfile
- Gemfile.lock
Diff: https://github.com/bbatsov/rubocop/compare/v0.41.2...v0.44.1
> Upgrade Rubocop to v0.44.1

- Gemfile
- Gemfile.lock
Ports https://github.com/codeclimate/codeclimate-rubocop/pull/77 over to this channel.
> [cache-support] Upgrade Rubocop to latest version

- lib/cc/engine/rubocop.rb
Fixes https://github.com/codeclimate/codeclimate-rubocop/issues/97
> Fix activesupport load-ordering bug

- Gemfile
- Gemfile.lock
- bin/newver
> Updated channel and documentation to Rubocop v0.70

- Gemfile
- Gemfile.lock
> Fix 0.69 versions

- Gemfile.lock
Re: https://github.com/codeclimate/codeclimate-rubocop/issues/176
> Update rubocop-rspec - 68

- Gemfile
- Gemfile.lock
> Add rubocop-rails to channel/rubocop-0-71

- Gemfile
- Gemfile.lock
re: https://github.com/codeclimate/codeclimate-rubocop/issues/178#issuecomment-499166362
> Add rubocop-rails to avoid confusion

- Gemfile
- Gemfile.lock
- config/contents/layout/empty_lines_around_attribute_accessor.md
- config/contents/layout/first_argument_indentation.md
- config/contents/lint/deprecated_open_ssl_constant.md
- config/contents/style/and_or.md
- config/contents/style/double_negation.md
- spec/cc/engine/config_upgrader_spec.rb
- spec/cc/engine/rubocop_spec.rb
- spec/support/currently_undocumented_cops.txt
Based on https://github.com/codeclimate/codeclimate-rubocop/pull/237
> Updated channel and documentation to Rubocop v0.84.0

- Gemfile
- Gemfile.lock
Requested at https://github.com/codeclimate/codeclimate-rubocop/issues/231
> Add rubocop-sequel support for rubocop's 0.85

- Gemfile
- Gemfile.lock
Requested at https://github.com/codeclimate/codeclimate-rubocop/issues/231
> Add rubocop-sequel support for rubocop's 0.87

- Gemfile
- Gemfile.lock
- config/contents/layout/multiline_operation_indentation.md
- config/contents/layout/space_before_brackets.md
- config/contents/lint/deprecated_constants.md
- config/contents/lint/lambda_without_literal_block.md
- config/contents/lint/non_deterministic_require_order.md
- config/contents/lint/redundant_dir_glob_sort.md
- config/contents/style/endless_method.md
- config/contents/style/explicit_block_argument.md
- config/contents/style/single_line_methods.md
- spec/support/config_upgrader_rubocop.yml
As usual, I'll create the correct base branch and update the PR before merging.
> Updated channel and documentation to Rubocop v1.8.1

- Gemfile
- Gemfile.lock
- config/contents/layout/first_argument_indentation.md
- config/contents/lint/number_conversion.md
- config/contents/lint/numbered_parameter_assignment.md
- config/contents/lint/or_assignment_to_constant.md
- config/contents/lint/symbol_conversion.md
- config/contents/lint/triple_quotes.md
- config/contents/naming/variable_number.md
- config/contents/style/ascii_comments.md
- config/contents/style/disable_cops_within_source_code_directive.md
- config/contents/style/eval_with_location.md
- config/contents/style/float_division.md
- config/contents/style/format_string_token.md
- config/contents/style/if_with_boolean_literal_branches.md
- config/contents/style/non_nil_check.md
- config/contents/style/numeric_predicate.md
- config/contents/style/single_line_methods.md
- spec/support/config_upgrader_rubocop.yml
As usual, I'll create the correct base branch and update the PR before merging.
> Updated channel and documentation to Rubocop v1.9.1

- Gemfile
- Gemfile.lock
- config/contents/gemspec/date_assignment.md
- config/contents/layout/multiline_assignment_layout.md
- config/contents/lint/debugger.md
- config/contents/lint/multiple_comparison.md
- config/contents/style/constant_visibility.md
- config/contents/style/double_negation.md
- config/contents/style/eval_with_location.md
- config/contents/style/exponential_notation.md
- config/contents/style/hash_conversion.md
- spec/support/config_upgrader_rubocop.yml
As usual, I'll create the correct base branch and update the PR before merging.
> Updated channel and documentation to Rubocop v1.10

- Gemfile
- Gemfile.lock
Addresses https://github.com/codeclimate/codeclimate-rubocop/issues/268
> Add support for rubocop-graphql

- Gemfile
- Gemfile.lock
- config/contents/bundler/duplicated_gem.md
- config/contents/layout/extra_spacing.md
- config/contents/lint/debugger.md
- config/contents/lint/duplicate_branch.md
- config/contents/style/endless_method.md
- config/contents/style/hash_conversion.md
- config/contents/style/symbol_proc.md
- config/contents/style/unless_logical_operators.md
I am unsure which branch to target, does a `codeclimate:channel/rubocop-1-11-0` branch need to be made on the base repository?
I am currently targeting `channel/rubocop-1-10-0` because that is where I branched from.
> Add channel/rubocop-1-11-0

- Gemfile
- Gemfile.lock
- config/contents/lint/suppressed_exception.md
- config/contents/lint/symbol_conversion.md
- config/contents/naming/memoized_instance_variable_name.md
- config/contents/naming/rescued_exceptions_variable_name.md
- config/contents/style/documentation.md
- config/contents/style/method_call_with_args_parentheses.md
- config/contents/style/redundant_self.md
- config/contents/style/string_chars.md
- config/contents/style/trailing_body_on_method_definition.md
- spec/support/config_upgrader_rubocop.yml
- Adds channel/rubocop-1-12-0
@fede-moya I don't know if I got ahead of myself and maybe these channels shouldn't be created until #279 is merged? Or I think they may need to be rebased after the merge. 
This currently includes the work in #279 because I used that to branch from.
> Add channel/rubocop-1-12-0

- Gemfile
- Gemfile.lock
- config/contents/style/access_modifier_declarations.md
- config/contents/style/frozen_string_literal_comment.md
- config/contents/style/method_call_with_args_parentheses.md
Currently targeting `channel/rubocop-1-12-0` because I do not see `channel/rubocop-1-12-1`.
> Add channel/rubocop-1-12-1

- Gemfile
- Gemfile.lock
> Update rubocop to 1.22.3

- Gemfile
- Gemfile.lock
- config/contents/naming/block_forwarding.md
- config/contents/style/hash_syntax.md
- config/contents/style/if_with_boolean_literal_branches.md
- config/contents/style/method_call_with_args_parentheses.md
> Update rubocop to 1.25.0

- Gemfile
- Gemfile.lock
- config/contents/naming/method_parameter_name.md
> Update rubocop to 1.25.1

- Gemfile
- Gemfile.lock
- config/contents/gemspec/dependency_version.md
- config/contents/gemspec/ruby_version_globals_usage.md
- config/contents/lint/ambiguous_range.md
- config/contents/lint/loop.md
- config/contents/lint/non_deterministic_require_order.md
- config/contents/lint/or_assignment_to_constant.md
- config/contents/lint/raise_exception.md
- config/contents/naming/variable_name.md
- config/contents/naming/variable_number.md
- config/contents/security/yaml_load.md
- config/contents/style/and_or.md
- config/contents/style/case_like_if.md
- config/contents/style/date_time.md
- config/contents/style/double_negation.md
- config/contents/style/env_home.md
- config/contents/style/fetch_env_var.md
- config/contents/style/identical_conditional_branches.md
- config/contents/style/optional_arguments.md
- config/contents/style/optional_boolean_parameter.md
- config/contents/style/safe_navigation.md
- config/contents/style/string_chars.md
- spec/support/config_upgrader_rubocop.yml
> Update rubocop to 1.29.0

- Gemfile
- Gemfile.lock
- config/contents/lint/empty_conditional_body.md
- config/contents/lint/shadowed_exception.md
- config/contents/style/numeric_literals.md
> Update rubocop to 1.34.1

- Gemfile
- Gemfile.lock
- config/contents/layout/line_length.md
- config/contents/lint/erb_new_arguments.md
- config/contents/style/hash_syntax.md
- config/contents/style/magic_comment_format.md
> Update rubocop to 1.35.0

- Gemfile.lock
> Update rubocop plugins

- Gemfile
- Gemfile.lock
Add `rubocop-factory_bot` gem for more flexibility.
> Add rubocop-factory_bot gem
