codeclimate/codeclimate-rubocop

- spec/cc/engine/rubocop_spec.rb
I was having issues and discovered that one of these test was a false positive. I then added another test to confirm that `.rubocop.yml` is used without specifying it in the config.
> Improve tests around rubocop.yml config files

- lib/cc/engine/rubocop.rb
- lib/rubocop/cop/method_complexity_patch.rb
Bryan [suggested this](https://github.com/codeclimate/codeclimate-rubocop/pull/9#discussion-diff-37535714R4) as a refactor as it will fail faster if RuboCop changes in the future, and it will fail in a more obvious way (rather than just suddenly failing one of our analysis specs). Seems sound to me.
This won't affect current behavior, just guard a bit against future failure, so there's no rush in merging or deploying.
> change monkey patch to use module_eval

- Dockerfile
- README.md
@codeclimate/review Updates badge link
> update badge link

- circle.yml
Doing all of this in Circle turned out to be a pain to get working correctly, and would have been even more of a pain to expand to other repos, so I'm backing out those bits.
Eventually, it would be good to have all of those various tasks centralized: once we do that elsewhere, we can remove the `deployment` bit entirely here. In the meantime, we should keep the existing behavior.
> circleci: don't tag to git or deploy to docker hub

- lib/cc/engine/file_list_resolver.rb
- lib/cc/engine/rubocop.rb
- spec/cc/engine/rubocop_spec.rb
> Removes non-Ruby files from include_path before passing to rubocop.

- .rubocop.yml
- Rakefile
- bin/codeclimate-rubocop
- lib/cc/engine/file_list_resolver.rb
- lib/cc/engine/rubocop.rb
- lib/rubocop/cop/method_complexity_patch.rb
- spec/cc/engine/rubocop_spec.rb
It seems only fitting that the RuboCop engine should pass its own checks!
I added a minimal configuration based on the current code, then ran
RuboCop using the `-a` (autocorrect) option.
The only non-stylistic change I made was to use an `any?` block in place
of a `detect` block combined with `!!`.
There are two violations remaining, both about method length, but
since there’s a little more involved I’ve left them alone.
> Add RuboCop configuration and basic style corrections

- lib/cc/engine/lockfile_specs.rb
- lib/cc/engine/rubocop.rb
- spec/cc/engine/lockfile_specs_spec.rb
- spec/cc/engine/rubocop_spec.rb
- spec/fixtures/Gemfile.lock
- spec/fixtures/Gemfile.lock.with_merge_conflicts
Only include the Rails-specific cops if we see railties in the Gemfile.lock file in the project. This should resolve cases where Rails-specific advice is given for projects that aren't using Rails (e.g. Rails/Delegate).
> Conditionally include Rails cops

- lib/cc/engine/lockfile_specs.rb
I'm running into the following error while running this engine locally through the platform. Looks like the `LockfileParser` depends upon some other classes defined in bundler that aren't brought in unless you `require "bundler"`.
```
/usr/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/lockfile_parser.rb:86:in `<class:LockfileParser>': uninitialized constant Bundler::Source (NameError)
from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/lockfile_parser.rb:14:in `<module:Bundler>'
from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/lockfile_parser.rb:13:in `<top (required)>'
from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
from …
```
> Add bundler to Gemfile and require for LockfileParser dependencies

- lib/cc/engine/lockfile_specs.rb
I was seeing a crash locally analyzing a repo with no Gemfile. It appears that Bundler's LockfileParser was actually trying to read a file somewhere even though we gave it string contents.
This changes the no-file behavior to be a harder short-circuit, so Bundler's class is never even instantiated.
I believe that we're not seeing this in production because production looks like it's still using [`b18`](https://github.com/codeclimate/builder/blob/master/config/engines.yml#L1-L2).
I believe the specs were passing because we were probably using a slightly different version of bundler there. I'm not certain, though. Similar to the last fix for this, this is not very unit-testable.
The stack trace:
```
/usr/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler.rb:198:in `rescue in root': Could …
```
> lockfile: fix no-Gemfile case

- config/cops.yml
- lib/cc/engine/rubocop.rb
This adds `config/cops.yml` which contains the configuration of the
points that each cop should return.
This also ups the default remediation points value to `200,000` from `50,000` since the previous value was too small to affect ratings.
> Add configurable remediation points from yaml

- .rubocop.yml
- Gemfile
- Gemfile.lock
- config/cops.yml
- lib/cc/engine/rubocop.rb
- lib/cc/engine/violation_decorator.rb
- spec/cc/engine/violation_decorator_spec.rb
This adds a check for the format of `[score/limit]` in a cop message and
will extract the `score` value and multiply it by the defined remediation
points.
Remediation points for metric cops were also tweaked to make up for the addition of multiplication.
> Allow remediation points to be multipliable

- circle.yml
Not overriding the dependency step can cause Circle to infer ruby and run a
bundle install. That can leave files in the source tree that end up copied into
the docker image and mess with bundler's operation within that image.
Also, the build step is (IMO) a dependency, not itself a test.
/cc @codeclimate/review -- open to opinions here
> Run docker build as a dependency, not a test step

- lib/cc/engine/violation_decorator.rb
we're loading SafeYAML, but then don't actually specify safe mode when
loading. We should just set it to the default when we load it.
cc @codeclimate/review
> SafeYAML: set safe mode by default

- lib/cc/engine/rubocop.rb
- spec/cc/engine/rubocop_spec.rb
When a line is skipped locally using Rubocops local disable we don't
want to report it. Rubocop offenses give us the `disabled?` method to
check if a violation was skipped locally.
> Skip locally disabled cops

- config/cops.yml
- spec/cc/engine/rubocop_spec.rb
Tune complexity points, following calculation function in [codeclimate-eslint](https://github.com/codeclimate/codeclimate-eslint/blob/master/lib/checks.js#L117), creating more parity with Ruby analysis in Code Climate classic.
cc @codeclimate/review @noahd1
> Tune remediation points

- README.md
> link to codelcimate docs in readme

- Gemfile.lock
There are some incompatibilites between the latest version of RuboCop
and rubocop-rspec which were fixed in this release.
See: https://github.com/nevir/rubocop-rspec/issues/62
> Update rubocop-rspec to 1.4.0

- .dockerignore
- Dockerfile
- Makefile
- bin/codeclimate-rubocop
- circle.yml
@codeclimate/review a couple things here around organization & building. Just cleaning up & making things a bit more consistent with other engines.
> Build cleanup

- lib/cc/engine/file_list_resolver.rb
- spec/cc/engine/rubocop_spec.rb
When paths were sent in as relative paths from the CLI, `Exclude`
directives within a rubocop config yml were not correctly applied. This
is because Rubocop internally turns those excludes into absolute paths,
and it seems like it was then trying to match the being-analyzed
relative path against the had-been-made-absolute excluded path.
@codeclimate/review haven't been able to get a spec breaking this, unfortunately. But have reproduced behavior & confirmed this fixes it. Thoughts?
> Resolve all paths to absolute paths

- lib/cc/engine/file_list_resolver.rb
- spec/cc/engine/rubocop_spec.rb
Engine-visible `exclude_paths` have been deprecated for a while, and
we've been removing support from a bunch of engines. Engines should now
rely on `include_paths`, which the CLI will calculate based on the
`exclude_paths` in `.codeclimate.yml`.
> Drop support for "exclude_paths" in engine config

- lib/cc/engine/file_list_resolver.rb
- spec/cc/engine/file_list_resolver_spec.rb
- spec/cc/engine/rubocop_spec.rb
- spec/spec_helper.rb
- spec/support/filesystem_helpers.rb
A couple crashes came up this morning as a result of non-existent files trying to be read by the file list resolver. This bug surfaced because of the changes to trying to make all paths absolute.
Took the opportunity to test this class more broadly, as well.
> FileListResolver: handle non-existent files

- Gemfile
- Gemfile.lock
Parser has a bug with out of range characters that was fixed in
2.3.0.5. This fix sets the version requirement for parser to be
~> 2.3.0.5.
See: https://github.com/bbatsov/rubocop/issues/2833
> Upgrade parser gem

- lib/cc/engine/category_parser.rb
* Rename cop method to namespace
c/ @codeclimate/review
> Move Lint/Eval to the Security category

- .rubocop.yml
- lib/cc/engine/file_list_resolver.rb
- spec/cc/engine/file_list_resolver_spec.rb
RuboCop's ConfigStore will sometimes return conflicting answers for
file_to_exclude and file_to_include so check file_to_exclude explicitly
and skip the file in question if it returns true.
c/ @codeclimate/review
> Explicitly check RuboCop excludes

- .rubocop.yml
- base_rubocop.yml
- bin/codeclimate-rubocop
- lib/cc/engine/fingerprint.rb
- lib/cc/engine/issue.rb
- lib/cc/engine/rubocop.rb
- lib/tasks/docs.rake
- spec/cc/engine/issue_spec.rb
- spec/cc/engine/rubocop_spec.rb
This PR implements override fingerprints for method and class-based offenses, incorporating the path, check name, and offense message.
@codeclimate/review :mag_right:
> Add path-based fingerprint override for method/class offenses

- Gemfile
- Gemfile.lock
- lib/cc/engine/source_file.rb
This is the logic that we're replacing, plus smart reading of .ruby-version if
present and not overridden by the AllCops rule.
Required updating rubocop to [0.41.2](https://github.com/bbatsov/rubocop/blob/master/CHANGELOG.md#0412-2016-07-07)
/cc @codeclimate/review can I get a second set of eyes down the rubocop
CHANGELOG to see if I missed any compatibility concerns?
TODO: update docs.codeclimate.com
> Use Config#target_ruby_version

- .codeclimate.yml
- lib/cc/engine/fingerprint.rb
- spec/cc/engine/fingerprint_spec.rb
A user may elect more detailed messaging in RuboCop output by configuring:
AllCops:
DisplayCopNames: true
DisplayStyleGuide: true
ExtraDetails: true
which adds a url to issue messages, part of the fingerprint compute.
To correctly compute fingerprints in this case, we need an extra strip step.
@codeclimate/review 
cc @almostwhitehat with a thanks for finding this bug.
> Correctly strip detailed message in fingerprint

- Gemfile
- Gemfile.lock
- lib/cc/engine/category_parser.rb
Hi!
We want to start using a new rubocop extension we developed (https://rubygems.org/gems/rubocop-migrations). It is a simple gem that disallows index removal from rails migrations (so you don't accidentally remove an index that is being used).
Given that we use codeclimate, it would be nice to be able to use that there.
> Add RuboCop Migrations

- circle.yml
This moves Rubocop to use Patrick & support automatic channel deployments based on branch name
> Support automatic channel building for rubocop

- Dockerfile
...to use code's bundle, which may include rubocop extensions.
> Add GEM_PATH env var to Dockerfile

- lib/cc/engine/fingerprint.rb
Noticed in a recent build that this cop is showing up as fixed/new
rather than changed. It was added in RuboCop v0.44, which we just
upgraded to.
> Override default fingerprinting for Metrics/BlockLength

- Gemfile
- Gemfile.lock
We're a point release behind, and this provides improvements around
parsing `&.` See [full changes][1].
[1]: https://github.com/whitequark/parser/compare/v2.3.3.1...v2.4.0.0
> Update Parser gem

- Gemfile
- Gemfile.lock
- Makefile
- config/contents/layout/indent_array.md
- config/contents/lint/uri_escape_unescape.md
- config/contents/rails/date.md
- config/contents/rails/inverse_of.md
- config/contents/rails/redundant_receiver_in_with_options.md
- config/contents/rails/request_referer.md
- config/contents/style/format_string_token.md
- config/contents/style/frozen_string_literal_comment.md
- config/contents/style/if_unless_modifier.md
- config/contents/style/method_def_parentheses.md
- config/contents/style/multiline_ternary_operator.md
- spec/support/currently_undocumented_cops.txt
The change to the Makefile is to avoid this issue with building the docs, caused by `rake` being in the `:test` Gemfile group.
```Executing busybox-1.24.2-r13.trigger
OK: 38 MiB in 34 packages
bundler: failed to load command: rake (/usr/local/bin/rake)
Gem::Exception: can't find executable rake for gem rake. rake is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
/usr/local/bundle/gems/bundler-1.16.1/lib/bundler/rubygems_integration.rb:458:in `block in replace_bin_path'
/usr/local/bundle/gems/bundler-1.16.1/lib/bundler/rubygems_integration.rb:478:in `block in replace_bin_path'
/usr/local/bin/rake:23:in `<top (required)>'
make: *** [docs] Error 1
```
> Updated engine and docs for Rubocop v0.52.1.

- Dockerfile
Rubocop versions after 0.56.x have a native gem dependency.
The `build-base` package provides the necessary toolchain.
We remove it after use to reduce the size of the image.
> Install basic build dependencies prior to building gems.

- DEVELOPERS.md
- README.md
- lib/tasks/docs.rake
Just updates URL and Markdown syntax.
> Small text adjustments

- Gemfile
- Gemfile.lock
Hey folks 👋
I don't know if this commit is valid. 
We use rubocop-minitest and it would be great if codeclimate could support it.
This commit includes rubocop-minitest gem in the Gemfile to allow
users that uses it to have their code analyzed with CodeClimate.
> Add RubocopMinitest

- Gemfile
- Gemfile.lock
Adding in a couple more really useful rubocop extensions that would be nice to be default supported.
> Support the thread_safety and i18n rubocop extensions.

- Dockerfile
Fix
```
engine rubocop failed with status 1 and stderr
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rubocop (LoadError)
from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /usr/src/app/lib/cc/engine/rubocop.rb:6:in `<top (required)>'
from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /usr/src/app/bin/codeclimate-rubocop:8:in `<main>'
```
> Pin bundler binary

- Gemfile
- Gemfile.lock
- config/contents/layout/empty_lines_around_attribute_accessor.md
- config/contents/layout/multiline_operation_indentation.md
- config/contents/layout/trailing_whitespace.md
- config/contents/lint/empty_when.md
- config/contents/lint/literal_as_condition.md
- config/contents/lint/parentheses_as_grouped_expression.md
- config/contents/style/guard_clause.md
- config/contents/style/multiline_when_then.md
- config/contents/style/optional_arguments.md
- config/contents/style/slicing_with_range.md
- spec/cc/engine/config_upgrader_spec.rb
This PR proposes to update the Rubocop integration to support v0.83.0. It includes commits from #234 as well, but I'm happy to rework the PR to do a straight upgrade from the 0-81 channel if that's preferable.
> Updated channel and documentation to Rubocop v0.83.0

- Gemfile
- Gemfile.lock
Requested in #217
I could use it in our project as well.
When I include rubocop-rake in our .rubocop.yml require section, the rubocop step in codeclimate fails with:
>/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require': cannot load such file -- rubocop-rake (LoadError)
Since this code runs separately from our codebase, I realized it doesn't matter what I include in our Gemfile. This gem must be included here.
@filipesperandio opening against latest channel
> Support rubocop-rake

- Gemfile
- Gemfile.lock
- config/contents/bundler/gem_comment.md
- config/contents/layout/empty_lines_around_attribute_accessor.md
- config/contents/layout/first_argument_indentation.md
- config/contents/layout/first_parameter_indentation.md
- config/contents/layout/hash_alignment.md
- config/contents/layout/heredoc_indentation.md
- config/contents/layout/line_length.md
- config/contents/lint/ensure_return.md
- config/contents/lint/format_parameter_mismatch.md
- config/contents/lint/mixed_regexp_capture_types.md
- config/contents/naming/class_and_module_camel_case.md
- config/contents/style/copyright.md
- config/contents/style/double_negation.md
- config/contents/style/frozen_string_literal_comment.md
- config/contents/style/redundant_regexp_character_class.md
- config/contents/style/redundant_regexp_escape.md
- spec/cc/engine/config_upgrader_spec.rb
Based on https://github.com/codeclimate/codeclimate-rubocop/pull/238 which is actually pointing to rubocop `0.86`
[Official Rubocop release](https://github.com/rubocop-hq/rubocop/releases/tag/v0.85.0)
> Updated channel and documentation to Rubocop v0.85.1

- Gemfile
- Gemfile.lock
Requested at https://github.com/codeclimate/codeclimate-rubocop/issues/231
> Add rubocop-sequel support for rubocop's 0.86

- Gemfile
- Gemfile.lock
- config/contents/gemspec/required_ruby_version.md
- config/contents/lint/duplicate_elsif_condition.md
- config/contents/lint/non_deterministic_require_order.md
- config/contents/style/array_coercion.md
- config/contents/style/case_like_if.md
- config/contents/style/hash_as_last_array_item.md
- config/contents/style/hash_like_case.md
- config/contents/style/redundant_file_extension_in_require.md
- spec/cc/engine/config_upgrader_spec.rb
- spec/support/currently_undocumented_cops.txt
I'm a bit late on this one, and I feel like the Rubocop folks will be releasing v0.89 soon, but oh well!
As a side note, I've been patching the config-upgrader spec, in this and previous PRs, by appending any newly added cops to the ad hoc config file, and disabling them. Is this providing the desired "value" to the spec and/or functionality?
> Updated channel and documentation to Rubocop v0.88

- Gemfile
- Gemfile.lock
- config/contents/gemspec/required_ruby_version.md
- config/contents/lint/binary_operator_with_identical_operands.md
- config/contents/lint/duplicate_rescue_exception.md
- config/contents/lint/empty_conditional_body.md
- config/contents/lint/ensure_return.md
- config/contents/lint/float_comparison.md
- config/contents/lint/missing_super.md
- config/contents/lint/out_of_range_regexp_ref.md
- config/contents/lint/self_assignment.md
- config/contents/lint/top_level_return_with_argument.md
- config/contents/lint/unreachable_loop.md
- config/contents/style/explicit_block_argument.md
- config/contents/style/global_std_stream.md
- config/contents/style/optional_boolean_parameter.md
- config/contents/style/single_argument_dig.md
- config/contents/style/string_concatenation.md
- spec/cc/engine/config_upgrader_spec.rb
- spec/support/config_upgrader_rubocop.yml
A whole mess of new cops in this release. The config-upgrader spec is getting kind unwieldy, so I extracted the upgrader's `.rubocop.yml` to a fixture file. Happy to make any requested changes!
> Updated channel and documentation to Rubocop v0.89.1

- lib/cc/engine/rubocop.rb
- spec/cc/engine/config_upgrader_spec.rb
- spec/cc/engine/rubocop_spec.rb
In investigating [#251 Layout/FirstArgumentIndentation config options do not match rubocop mainline](#251) I learned we rely on the [Mry](https://github.com/pocke/mry) gem to automagically update RuboCop configs between as RuboCop version change. On one hand this is nice because it brings outdated configs inline with the newer versions of RuboCop without manually checking and updating all the changing configs. Unfortunately Mry hasn't been updated since RuboCop version 0.78 and it's not negatively changing some config values that have been further modified since 0.78. Mry also never supported splitting cops or deleting cops.  
In the case of the open issue here I think there was a combination of problems, one was with handling a split cop and the other is how it handles renamed cops that …
> make mry config upgrading optional

- Gemfile
- Gemfile.lock
Resolves #232 
Add's support for the [rubocop-sorbet](https://github.com/Shopify/rubocop-sorbet) plugin in channel `rubocop-0-92`.
I made a test project to run the codeclimate CLI against: https://github.com/britneywright/rubocop-sorbet-test
For local testing:
- Pull down this PR
- `IMAGE_NAME=codeclimate/codeclimate-rubocop-test make image`
- Pull down the [rubocop-sorbet-test](https://github.com/britneywright/rubocop-sorbet-test) project
- `bundle install`
- `codeclimate analyze -e rubocop-test --dev`
Should see an output similar to the following:
```
Starting analysis
Running rubocop-test: Done!
== Gemfile (2 issues) ==
1: No Sorbet sigil found in file. Try a `typed: true` to start (you can also use `rubocop -a` to automatically add this). [rubocop-test]
1: Prefer single-quoted strings …
```
> add support for rubocop-sorbet 0.5.1 (channel rubococp-0-92)

- README.md
The installation steps are outdated: `engines:enable` has been replaced for `engines:install` and it no longer add it to `codeclimate.yml.`
Disclaimer: this is NOT for hacktoberfest!
> Updates Readme's installation section

- Gemfile
- Gemfile.lock
- config/contents/bundler/gem_filename.md
- config/contents/layout/line_end_string_concatenation_indentation.md
- config/contents/layout/multiline_method_argument_line_breaks.md
- config/contents/lint/ambiguous_range.md
- config/contents/lint/debugger.md
- config/contents/lint/duplicate_branch.md
- config/contents/naming/inclusive_language.md
- config/contents/style/block_delimiters.md
- config/contents/style/comment_annotation.md
- config/contents/style/commented_keyword.md
- config/contents/style/eval_with_location.md
- config/contents/style/identical_conditional_branches.md
- config/contents/style/missing_else.md
- config/contents/style/mutable_constant.md
- config/contents/style/redundant_freeze.md
- config/contents/style/redundant_self_assignment_branch.md
- config/contents/style/special_global_vars.md
- config/contents/style/struct_inheritance.md
- config/contents/style/word_array.md
- spec/rubocop/config_patch_spec.rb
- spec/support/config_upgrader_rubocop.yml
Updates rubocop to [`v1.20.0`](https://github.com/rubocop/rubocop/releases/tag/v1.20.0). 
Currently targeting channel/rubocop-1-18-3 because channel/rubocop-1-20-0 does not exist yet.
> Add channel/rubocop-1-20-0

- Gemfile
- Gemfile.lock
- config/contents/bundler/insecure_protocol_source.md
- config/contents/lint/ambiguous_operator_precedence.md
- config/contents/lint/incompatible_io_select_with_fiber_scheduler.md
- config/contents/style/and_or.md
- config/contents/style/case_equality.md
- spec/support/config_upgrader_rubocop.yml
Updates rubocop to [`1.21.0`](https://github.com/rubocop/rubocop/releases/tag/v1.21.0).
> Add channel/rubocop-1-21-0

- Gemfile
- Gemfile.lock
- config/contents/gemspec/require_mfa.md
- config/contents/layout/empty_line_between_defs.md
- config/contents/lint/ambiguous_range.md
- config/contents/lint/number_conversion.md
- config/contents/lint/useless_ruby2_keywords.md
- config/contents/metrics/parameter_lists.md
- config/contents/naming/file_name.md
- config/contents/style/empty_method.md
- config/contents/style/open_struct_use.md
- spec/support/config_upgrader_rubocop.yml
> Update rubocop to 1.23.0

- Gemfile
This PR adds support for the rubocop-shopify gem, enabling the Shopify ruby style guide configuration.
To enable, add this configuration to the top of your `rubocop.yml` file:
```yaml
inherit_gem:
rubocop-shopify: rubocop.yml
```
> Add support for rubocop-shopify

- Gemfile
- Gemfile.lock
- config/contents/gemspec/require_mfa.md
- config/contents/layout/comment_indentation.md
- config/contents/lint/deprecated_class_methods.md
- config/contents/lint/incompatible_io_select_with_fiber_scheduler.md
- config/contents/naming/block_forwarding.md
- config/contents/security/open.md
- config/contents/style/character_literal.md
- config/contents/style/collection_compact.md
- config/contents/style/file_read.md
- config/contents/style/file_write.md
- config/contents/style/hash_syntax.md
- config/contents/style/map_to_hash.md
- config/contents/style/method_call_with_args_parentheses.md
- config/contents/style/method_def_parentheses.md
- config/contents/style/numeric_literals.md
- lib/cc/engine/content_resolver.rb
- spec/support/config_upgrader_rubocop.yml
- General bundle update for Ruby 3.1 compatibility.
- Fix a constant resolution issue with active_support 7.
> Update rubocop to 1.24.1

- Gemfile
- Gemfile.lock
- config/contents/lint/ambiguous_block_association.md
- config/contents/lint/debugger.md
- config/contents/lint/empty_conditional_body.md
- config/contents/lint/number_conversion.md
- config/contents/metrics/abc_size.md
- config/contents/metrics/block_length.md
- config/contents/metrics/method_length.md
- config/contents/naming/predicate_name.md
- config/contents/style/block_delimiters.md
- config/contents/style/class_equality_comparison.md
- config/contents/style/format_string_token.md
- config/contents/style/method_call_with_args_parentheses.md
- config/contents/style/method_call_without_args_parentheses.md
- config/contents/style/numeric_predicate.md
- config/contents/style/symbol_proc.md
> Update rubocop to 1.33.0

- Gemfile
- Gemfile.lock
Includes the standard gem for those who want to use it in rubocop (see here: https://github.com/testdouble/standard#usage-via-rubocop)
Addresses #351
> allow standard to be run with rubocop. Fixes #351

- Gemfile
- Gemfile.lock
- config/contents/lint/missing_super.md
- config/contents/metrics/collection_literal_length.md
- config/contents/naming/method_name.md
- config/contents/style/accessor_grouping.md
- config/contents/style/case_like_if.md
- config/contents/style/dir_empty.md
- config/contents/style/file_empty.md
- config/contents/style/if_unless_modifier.md
- config/contents/style/zero_length_predicate.md
> Update rubocop to 1.48.1

- Gemfile
- Gemfile.lock
* Repos that use rubocop-1-18-3 in analysis can now integrate `syntax_tree` into their rubocop configurations:
https://github.com/ruby-syntax-tree/syntax_tree#rubocop
> add `syntax_tree` gem for rubocop-1-18-3

- Gemfile
- Gemfile.lock
Same thing as #367 for the beta channel
Rubocop-rspec has extracted the rails cops to rubocop-rspec_rails
> the cops related to rspec-rails are aliased (RSpec/Rails/Foo == RSpecRails/Foo) until v3.0 is released
https://github.com/rubocop/rubocop-rspec/blob/master/CHANGELOG.md#2280-2024-03-30
So it would be nice to support it before v3 is released
> Add rubocop-rspec_rails to beta

- Gemfile
- Gemfile.lock
Rubocop-rspec has extracted the rails cops to rubocop-rspec_rails
> the cops related to rspec-rails are aliased (RSpec/Rails/Foo == RSpecRails/Foo) until v3.0 is released
https://github.com/rubocop/rubocop-rspec/blob/master/CHANGELOG.md#2280-2024-03-30
So it would be nice to support it before v3 is released
> Add rubocop-rspec_rails to channel/rubocop-1-56-3
